apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | default "production" | quote }}
