replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

config:
  # Postgres configs
  dbHost: "postgres-db-postgresql"
  dbPort: "5432"
  dbUser: "postgres"
  dbName: "postgres"
  dbPassword: "X4KCRdsj3gcwsvqGOpwil8Ue"

  # Redis configs
  redisHost: "redis-master"
  redisPort: "6379"
  redisPassword: "PFXbBtnTUXEUPFLgXovzG1Bi"

  # Storage
  s3Endpoint: "http://cluster.local"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "api.sandbox.reservoir"
      paths:
        - path: /
          pathType: Prefix

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podLabels:
            app.kubernetes.io/name: frontend
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infrastructure
          podLabels:
            app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podLabels:
            app.kubernetes.io/name: postgresql
        - podLabels:
            app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
    - to:
        - targetNamespace: infrastructure
          podLabels:
            app.kubernetes.io/name: garage
      ports:
        - protocol: TCP
          port: 3900

serviceAccount:
  create: true
  name: "backend-sa"

# placeholders
rbac:
  create: true

externalSecret:
  enabled: false
